### ISSUE TITLE
Add Commitees Model + CRUD

### ISSUE THREAD

**Issue by codingmickey** [djunicode/information-portal#10]
include attributes wrt this but not limited to

![Image](https://user-images.githubusercontent.com/42518907/229591073-bfdd71da-2962-4329-9651-08c62b61998e.png)

**Comment by codingmickey** [comment]
@maverick2903 I'm assigning you this.. when can it be completed by?

### Tasks
- [ ] mongoose model with proper schema
- [ ] Create Route
- [ ] Update Route
- [ ] Read Route
- [ ] Delete Route

**Comment by maverick2903** [comment]
Will try and finish it by this Sunday.
