### ISSUE TITLE
Add Projects Model + CRUD

### ISSUE THREAD

**Issue by codingmickey** [djunicode/information-portal#9]
include attributes wrt this but not limited to

![Image](https://user-images.githubusercontent.com/42518907/229590869-9c0b371e-82e1-46a5-bf30-36f85aae2748.png)

**Comment by codingmickey** [comment]
@KreenaShah I'm assigning you this.. when can it be completed by?

### Tasks
- [x] mongoose model with proper schema
- [x] Create Route
- [x] Update Route
- [x] Read Route
- [x] Delete Route

**Comment by KreenaShah** [comment]
By weekend
